# =========================================================
# Generated by the JuktiLang Compiler
# CSE-4114 Compiler Design and Construction Sessional
# Do not edit by hand — regenerate from the .jukti source.
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

pi = float(3.14159)
radius = float(4.5)
area = float(((pi * radius) * radius))
print(area)
