# =========================================================
# Generated by the JuktiLang Compiler
# CSE-4114 Compiler Design and Construction Sessional
# Do not edit by hand — regenerate from the .jukti source.
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

n = int(6)
result = int(1)
i = int(1)
while (i <= n):
    result = (result * i)
    i = (i + 1)
print(result)
