# =========================================================
# Generated by the JuktiLang Compiler
# CSE-4114 Compiler Design and Construction Sessional
# Do not edit by hand — regenerate from the .jukti source.
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

a = int(0)
b = int(1)
count = int(0)
limit = int(10)
while (count < limit):
    print(a)
    temp = int((a + b))
    a = b
    b = temp
    count = (count + 1)
rem = float((a - ((a / 2) * 2)))
if (rem == 0):
    print(1)
else:
    print(0)
