# =========================================================
# Generated by the JuktiLang Compiler
# CSE-4114 Compiler Design and Construction Sessional
# Do not edit by hand — regenerate from the .jukti source.
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

n = int(42)
if (n > 0):
    if (n > 100):
        print(2)
    else:
        print(1)
else:
    print(0)
