# =========================================================
# Generated by the JuktiLang Compiler
# CSE-4114 Compiler Design and Construction Sessional
# Do not edit by hand — regenerate from the .jukti source.
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

n = int(10)
sum = int(0)
i = int(1)
while (i <= n):
    sum = (sum + i)
    i = (i + 1)
print(sum)
