// codegen.cpp — owned by Sonia (Code Generation)
//
// Declarations become plain Python assignment with an explicit int()/
// float() cast so a সংখ্যা variable can never silently end up holding
// a Python float at runtime, even if an upstream semantic check were
// ever relaxed.

#include "codegen.h"
#include <iomanip>

CodeGenerator::CodeGenerator(ErrorHandler& errHandler) : err_(errHandler) {}

std::string CodeGenerator::indent() const {
    return std::string(indentLevel_ * 4, ' ');
}

void CodeGenerator::writeLine(const std::string& code) {
    out_ << indent() << code << "\n";
}

std::string CodeGenerator::generate(const ASTNodePtr& program) {
    out_.str("");
    out_.clear();
    indentLevel_ = 0;

    writeLine("# =========================================================");
    writeLine("# Generated by the JuktiLang Compiler");
    writeLine("# CSE-4114 Compiler Design and Construction Sessional");
    writeLine("# Do not edit by hand — regenerate from the .jukti source.");
    writeLine("# =========================================================");
    writeLine("import sys");
    writeLine("sys.stdout.reconfigure(encoding='utf-8')");
    writeLine("");

    if (!program) return out_.str();
    for (const auto& stmt : program->children) {
        genStatement(stmt);
    }
    return out_.str();
}

void CodeGenerator::genStatement(const ASTNodePtr& node) {
    if (!node) return;

    switch (node->type) {
        case NodeType::DECLARATION:     genDeclaration(node);     break;
        case NodeType::ASSIGNMENT:      genAssignment(node);      break;
        case NodeType::IF_STATEMENT:    genIfStatement(node);     break;
        case NodeType::WHILE_STATEMENT: genWhileStatement(node);  break;
        case NodeType::PRINT_STATEMENT: genPrintStatement(node);  break;
        default:
            err_.semanticError(node->line, node->column,
                "Code generation: unexpected node in statement position");
    }
}

void CodeGenerator::genBlock(const std::vector<ASTNodePtr>& stmts) {
    if (stmts.empty()) {
        writeLine("pass");
        return;
    }
    for (const auto& s : stmts) genStatement(s);
}

// ধরি সংখ্যা x = 5;   ->  x = int(5)
// ধরি সংখ্যা x;       ->  x = int(0)   (bare declaration gets a zero value)
void CodeGenerator::genDeclaration(const ASTNodePtr& node) {
    std::string typeFn = (node->declaredType == DataType::INT) ? "int" : "float";
    std::string rhs = node->valueExpr ? genExpression(node->valueExpr)
                                       : (node->declaredType == DataType::INT ? "0" : "0.0");
    writeLine(node->identifierName + " = " + typeFn + "(" + rhs + ")");
}

// x = expr;   ->  x = expr
void CodeGenerator::genAssignment(const ASTNodePtr& node) {
    writeLine(node->identifierName + " = " + genExpression(node->valueExpr));
}

// যদি (cond) { ... } [নাহলে { ... }]
void CodeGenerator::genIfStatement(const ASTNodePtr& node) {
    writeLine("if " + genExpression(node->condition) + ":");
    indentLevel_++;
    genBlock(node->thenBody);
    indentLevel_--;

    if (!node->elseBody.empty()) {
        writeLine("else:");
        indentLevel_++;
        genBlock(node->elseBody);
        indentLevel_--;
    }
}

// যতক্ষণ (cond) { ... }
void CodeGenerator::genWhileStatement(const ASTNodePtr& node) {
    writeLine("while " + genExpression(node->condition) + ":");
    indentLevel_++;
    genBlock(node->thenBody);
    indentLevel_--;
}

// দেখাও(expr);   ->  print(expr)
void CodeGenerator::genPrintStatement(const ASTNodePtr& node) {
    writeLine("print(" + genExpression(node->printExpr) + ")");
}

// ══════════════════════════════════════════════════════════════════
//  Expression code generation
// ══════════════════════════════════════════════════════════════════

std::string CodeGenerator::formatNumber(const ASTNodePtr& node) const {
    if (node->literalType == DataType::INT) {
        return std::to_string(static_cast<long long>(node->numberValue));
    }
    std::ostringstream ss;
    ss << std::fixed << std::setprecision(6) << node->numberValue;
    std::string s = ss.str();
    size_t dot = s.find('.');
    if (dot != std::string::npos) {
        size_t last = s.find_last_not_of('0');
        if (last == dot) last++;
        s = s.substr(0, last + 1);
    }
    return s;
}

std::string CodeGenerator::genExpression(const ASTNodePtr& node) {
    if (!node) return "None";

    switch (node->type) {
        case NodeType::NUMBER_LITERAL:
            return formatNumber(node);

        case NodeType::IDENTIFIER:
            return node->identifierName;

        case NodeType::UNARY_EXPR:
            return "(-" + genExpression(node->left) + ")";

        case NodeType::BINARY_EXPR:
        case NodeType::RELATIONAL_EXPR: {
            std::string left = genExpression(node->left);
            std::string right = genExpression(node->right);
            std::string op = node->op; // JuktiLang operators match Python's spelling
            return "(" + left + " " + op + " " + right + ")";
        }

        default:
            err_.semanticError(node->line, node->column,
                "Code generation: unexpected node in expression position");
            return "None";
    }
}
