# =========================================================
# Generated by the JuktiLang Compiler
# CSE-4114 Compiler Design and Construction Sessional
# Do not edit by hand — regenerate from the .jukti source.
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

x = int(5)
y = int(10)
print((x + y))
