# =========================================================
# Generated by the JuktiLang Compiler
# CSE-4114 Compiler Design and Construction Sessional
# Do not edit by hand — regenerate from the .jukti source.
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

a = int(12)
b = int(5)
print((a + b))
print((a - b))
print((a * b))
c = float((a / b))
print(c)
print(((a + b) * 2))
